version: '3.7'

services:
  backend-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/deploy-app/src
    ports:
      - 3000:3000

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginxconf:/etc/nginx/conf.d
